spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    url: jdbc:mysql://47.100.172.22:3306/eegSystem?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root123
    platform: mysql
    initialSize: 5
    minIdle: 5
    maxActive: 20
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.spring.eeg.mbg.model
server:
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /
  port: 8080
